### PR TITLE
Refactor css components

### PR DESCRIPTION
**Pull request by albertoescala**
I couldn't start the project but you can still review it. Tell what do you think.

### CODE REVIEW

**Comment by draperunner** [comment]
Hi! Thanks for contributing. I haven't tested this yet, but I don't think this will work. The project uses CSS Modules, which generates unique class names. If you inspect some components on https://kramster.it you'll see what I mean.

**Comment by albertoescala** [comment]
I want to start the project but I can't see it in my local. Do you know what is happening?

**Comment by draperunner** [comment]
If you run `npm install` and `npm start`, the app should start running on http://localhost:8080

The app will be pretty empty because you need to run the backend as well. The repo for it is here: https://github.com/draperunner/kramster-api, but the instructions are outdated for getting a database up and running. I might have a look at it later.

**Comment by draperunner** [comment]
I've pushed a commit (0b5500cbd124927938f9e7f7948a16be7433f024) to master that opens the browser automatically on `npm start`.

**Comment by albertoescala** [comment]
> If you run `npm install` and `npm start`, the app should start running on http://localhost:8080
> 
> The app will be pretty empty because you need to run the backend as well. The repo for it is here: https://github.com/draperunner/kramster-api, but the instructions are outdated for getting a database up and running. I might have a look at it later.

So the `README.md` is not updated. If I want to use another port, what I need to do?

**Comment by albertoescala** [comment]
I think it is working.
image

**Comment by albertoescala** [comment]
Yeah, you were right. It is not working 😞 . I will close both PRs.

**Comment by draperunner** [comment]
Okay, well thank you for the effort and happy Hacktoberfest. :)

**Pull request closed without merging**
